{
  "formatVersion": "1.1",
  "component": {
    "group": "com.2702rebels",
    "module": "canduitlib-java",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "canduitlib-java-0.0.3.jar",
          "url": "canduitlib-java-0.0.3.jar",
          "size": 5505,
          "sha512": "f31529ee6632a1edf5a3611c004a64fd96e88dbf8dbbde66faf904def0f85c2c03cfa6eb740651dcceb0a164f3390ff43565cd688c329416b9103ccdd30e21dd",
          "sha256": "7b299b156ba4398e400212132bf58696bf041c2afc6455f9c13e13b8bb581646",
          "sha1": "7445edba16cdeeebd9bb23ad506e9e16c4437bbb",
          "md5": "04aec2bb3cd298db77f33a698fd55284"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-2"
          }
        }
      ],
      "files": [
        {
          "name": "canduitlib-java-0.0.3.jar",
          "url": "canduitlib-java-0.0.3.jar",
          "size": 5505,
          "sha512": "f31529ee6632a1edf5a3611c004a64fd96e88dbf8dbbde66faf904def0f85c2c03cfa6eb740651dcceb0a164f3390ff43565cd688c329416b9103ccdd30e21dd",
          "sha256": "7b299b156ba4398e400212132bf58696bf041c2afc6455f9c13e13b8bb581646",
          "sha1": "7445edba16cdeeebd9bb23ad506e9e16c4437bbb",
          "md5": "04aec2bb3cd298db77f33a698fd55284"
        }
      ]
    }
  ]
}
