{
  "formatVersion": "1.1",
  "component": {
    "group": "canduit",
    "module": "CANduitLib-java",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "CANduitLib-java-0.0.1.jar",
          "url": "CANduitLib-java-0.0.1.jar",
          "size": 4980,
          "sha512": "4b6271f111d6eb6bce919266fce26a4f7c1a5f39e8afb1a6cd4347bb1a9775fe53b0ec330b38edc3e9f98f69515fffec77932db620a9e160d276eb2507eae8af",
          "sha256": "cd4818cdc16cf9bf9c45086c915ecf7f5336157deaddd9bd14a29acc1bf3b246",
          "sha1": "07e9221ad4fb142ca7b3dd41acd92aceb8c7b1af",
          "md5": "082a3c4f148ef4199a5c3bc7da40b990"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-2"
          }
        }
      ],
      "files": [
        {
          "name": "CANduitLib-java-0.0.1.jar",
          "url": "CANduitLib-java-0.0.1.jar",
          "size": 4980,
          "sha512": "4b6271f111d6eb6bce919266fce26a4f7c1a5f39e8afb1a6cd4347bb1a9775fe53b0ec330b38edc3e9f98f69515fffec77932db620a9e160d276eb2507eae8af",
          "sha256": "cd4818cdc16cf9bf9c45086c915ecf7f5336157deaddd9bd14a29acc1bf3b246",
          "sha1": "07e9221ad4fb142ca7b3dd41acd92aceb8c7b1af",
          "md5": "082a3c4f148ef4199a5c3bc7da40b990"
        }
      ]
    }
  ]
}
