{
  "formatVersion": "1.1",
  "component": {
    "group": "canduit",
    "module": "CANduitLib-java",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "CANduitLib-java-0.0.1.jar",
          "url": "CANduitLib-java-0.0.1.jar",
          "size": 4978,
          "sha512": "3931074612d5b92fafadd1389c1ad52d53861c6a871a5fc78f8fbb34ddb74233e26adc435306fdda2b2ace7641f7afbc0d853a0300d78345a7dfe55836a97a67",
          "sha256": "66ee51ee00ddeb23c2ec9492d349fb586bf8bce38c78331dc1e921447dd625c1",
          "sha1": "0a861e556464c5b4a91cee18002d9fc31f6cac56",
          "md5": "4e92b194ef7618ce5224dd0e98d95999"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-2"
          }
        }
      ],
      "files": [
        {
          "name": "CANduitLib-java-0.0.1.jar",
          "url": "CANduitLib-java-0.0.1.jar",
          "size": 4978,
          "sha512": "3931074612d5b92fafadd1389c1ad52d53861c6a871a5fc78f8fbb34ddb74233e26adc435306fdda2b2ace7641f7afbc0d853a0300d78345a7dfe55836a97a67",
          "sha256": "66ee51ee00ddeb23c2ec9492d349fb586bf8bce38c78331dc1e921447dd625c1",
          "sha1": "0a861e556464c5b4a91cee18002d9fc31f6cac56",
          "md5": "4e92b194ef7618ce5224dd0e98d95999"
        }
      ]
    }
  ]
}
