{
  "formatVersion": "1.1",
  "component": {
    "group": "canduit",
    "module": "canduitlib-java",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "canduitlib-java-0.0.1.jar",
          "url": "canduitlib-java-0.0.1.jar",
          "size": 4978,
          "sha512": "5d6f24c41739004bb02190d96703f37a5cb33224e58903e7cbb3868b3f2f7d3274a5d557bb9e1c4b8e94c24bb50aea27149bf9b8ad242c17c6d696463802d7d6",
          "sha256": "119fd9394c99c1d1ce4a0f25b40028f449345b59b6db9fb33a05cdf5dbae0940",
          "sha1": "c6d9cb8f0e287d572cb75674f2d5d99f0b24beb6",
          "md5": "725c79b95a18047046f2161e43a9085a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-2"
          }
        }
      ],
      "files": [
        {
          "name": "canduitlib-java-0.0.1.jar",
          "url": "canduitlib-java-0.0.1.jar",
          "size": 4978,
          "sha512": "5d6f24c41739004bb02190d96703f37a5cb33224e58903e7cbb3868b3f2f7d3274a5d557bb9e1c4b8e94c24bb50aea27149bf9b8ad242c17c6d696463802d7d6",
          "sha256": "119fd9394c99c1d1ce4a0f25b40028f449345b59b6db9fb33a05cdf5dbae0940",
          "sha1": "c6d9cb8f0e287d572cb75674f2d5d99f0b24beb6",
          "md5": "725c79b95a18047046f2161e43a9085a"
        }
      ]
    }
  ]
}
