{
  "formatVersion": "1.1",
  "component": {
    "group": "canduit",
    "module": "canduitlib-java",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "canduitlib-java-0.0.1.jar",
          "url": "canduitlib-java-0.0.1.jar",
          "size": 4993,
          "sha512": "ec973464b40d2383ad4fb9dffe165dfbe1022a951a8d5ceeb23548dc5aeb57401cd812f9fe1dfd9c4048abdc01b43369180ee56d9b629bd5559beaf8e1256ea2",
          "sha256": "906dd07c85e5ba5a4b2ce0eb11e3a985f178b0f898bad7c9708d171ebab419a8",
          "sha1": "d4e0561e8e5da65b6e78111ae5ee22697a8fa579",
          "md5": "d4364f658e254a1fba8f5f0d1c75e9a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-2"
          }
        }
      ],
      "files": [
        {
          "name": "canduitlib-java-0.0.1.jar",
          "url": "canduitlib-java-0.0.1.jar",
          "size": 4993,
          "sha512": "ec973464b40d2383ad4fb9dffe165dfbe1022a951a8d5ceeb23548dc5aeb57401cd812f9fe1dfd9c4048abdc01b43369180ee56d9b629bd5559beaf8e1256ea2",
          "sha256": "906dd07c85e5ba5a4b2ce0eb11e3a985f178b0f898bad7c9708d171ebab419a8",
          "sha1": "d4e0561e8e5da65b6e78111ae5ee22697a8fa579",
          "md5": "d4364f658e254a1fba8f5f0d1c75e9a0"
        }
      ]
    }
  ]
}
