{
  "formatVersion": "1.1",
  "component": {
    "group": "com.2702rebels",
    "module": "canduitlib-java",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "canduitlib-java-0.0.4.jar",
          "url": "canduitlib-java-0.0.4.jar",
          "size": 6168,
          "sha512": "bff8ba78f92ac90c946e97ff52d949ae101e1dd6c311e1ed5d5c5b5a17df341cea93d2166135ef8da5a1af618051592600fe533c6a80a2635580262d61a63bf2",
          "sha256": "f4f9e1360dbdc992e66c78ad43d6cf7926d5902b1a734173136ed9af13989df7",
          "sha1": "0067ba64c7b78d3614ee6c5ab9ccb17a4cdbdc3d",
          "md5": "39497cc7b9396bed57aae305a33278bc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-2"
          }
        }
      ],
      "files": [
        {
          "name": "canduitlib-java-0.0.4.jar",
          "url": "canduitlib-java-0.0.4.jar",
          "size": 6168,
          "sha512": "bff8ba78f92ac90c946e97ff52d949ae101e1dd6c311e1ed5d5c5b5a17df341cea93d2166135ef8da5a1af618051592600fe533c6a80a2635580262d61a63bf2",
          "sha256": "f4f9e1360dbdc992e66c78ad43d6cf7926d5902b1a734173136ed9af13989df7",
          "sha1": "0067ba64c7b78d3614ee6c5ab9ccb17a4cdbdc3d",
          "md5": "39497cc7b9396bed57aae305a33278bc"
        }
      ]
    }
  ]
}
