{
  "formatVersion": "1.1",
  "component": {
    "group": "com.2702rebels",
    "module": "canduitlib-java",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "canduitlib-java-0.0.2.jar",
          "url": "canduitlib-java-0.0.2.jar",
          "size": 4993,
          "sha512": "a2873be949585fb344b79db309c186d430bf2dbc8986a37a8fb48d8d4e444a20966fefc24a1fdb1612626f4b9d30cbd8a0c4f23be9fb5e54cee5f1f00cb63a03",
          "sha256": "2bb9a21f9033f719dc73e6c5d195ef60c935dcab72dc894f8f6145c92f5e9b2a",
          "sha1": "3ee3d0790a819be1e2fd7c7b6a9d55bcac8fc777",
          "md5": "725459f8497f40d295ad1ee9c80aaac0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.+"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-2"
          }
        }
      ],
      "files": [
        {
          "name": "canduitlib-java-0.0.2.jar",
          "url": "canduitlib-java-0.0.2.jar",
          "size": 4993,
          "sha512": "a2873be949585fb344b79db309c186d430bf2dbc8986a37a8fb48d8d4e444a20966fefc24a1fdb1612626f4b9d30cbd8a0c4f23be9fb5e54cee5f1f00cb63a03",
          "sha256": "2bb9a21f9033f719dc73e6c5d195ef60c935dcab72dc894f8f6145c92f5e9b2a",
          "sha1": "3ee3d0790a819be1e2fd7c7b6a9d55bcac8fc777",
          "md5": "725459f8497f40d295ad1ee9c80aaac0"
        }
      ]
    }
  ]
}
